# Generated by Django 4.1.13 on 2023-12-07 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AircraftNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tail_number", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("incoming", "Incoming"),
                            ("departing", "Departing"),
                            ("quickturn", "Quickturn"),
                            ("off_ramp", "Off-Ramp"),
                            ("standby", "Standby"),
                            ("maintenance", "Maintenance"),
                            ("overnight", "Overnight"),
                        ],
                        max_length=20,
                    ),
                ),
                ("service_time", models.DateTimeField()),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("hanger_1", "H1"),
                            ("hanger_2", "H2"),
                            ("hanger_3", "H3"),
                            ("hanger_4", "H4"),
                            ("row_1", "R1"),
                            ("row_2", "R2"),
                            ("row_3", "R3"),
                            ("row_4", "R4"),
                            ("row_5", "R5"),
                            ("row_6", "R6"),
                            ("tie_down", "T-D"),
                            ("gama", "Gama"),
                            ("off_ramp", "O-R"),
                            ("customs", "Cstm"),
                            ("netjets", "NJ"),
                        ],
                        max_length=30,
                    ),
                ),
                ("aircraft_model", models.CharField(max_length=50)),
                (
                    "eta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Estimated Time of Arrival"
                    ),
                ),
                (
                    "etd",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Estimated Time of Departure",
                    ),
                ),
                ("passenger_count", models.IntegerField(blank=True, null=True)),
                (
                    "fuel_qty",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Fuel Quantity"
                    ),
                ),
                (
                    "fuel_format",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lbs", "lbs"),
                            ("kgs", "kgs"),
                            ("gallons", "gallons"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("jet_a_neg", "Jet-"),
                            ("jet_a_pos", "Jet+"),
                            ("avgas", "Avgas"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "lav_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("fwr", "Fwr"),
                            ("aft", "Aft"),
                            ("fwr_aft", "Fwr & Aft"),
                            ("completed", "Completed"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "lav_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full", "Full"),
                            ("dump", "Dump"),
                            ("rinse", "Rinse"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("lav_gallons", models.IntegerField(blank=True, null=True)),
                (
                    "water_service_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "gpu_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("stage", "Stage"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "catering_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "catering_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("pic", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "customer_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("based_tenant", "Based Tenant"),
                            ("signature_silver", "Signature Status Silver"),
                            ("signature_gold", "Signature Status Gold"),
                            ("signature_platinum", "Signature Status Platinum"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "oil_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("oil_type", models.CharField(blank=True, max_length=50, null=True)),
                ("oil_qty", models.IntegerField(blank=True, null=True)),
                (
                    "ladder_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "vacuum_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
