# Generated by Django 4.1.13 on 2023-12-12 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("aircraft", "0002_aircraftnote_transportation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aircraftnote",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="aircraftnote",
            name="service_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Service Time"
            ),
        ),
        migrations.AlterField(
            model_name="aircraftnote",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("incoming", "Incoming"),
                    ("departing", "Departing"),
                    ("quickturn", "Quickturn"),
                    ("off_ramp", "Off-Ramp"),
                    ("standby", "Standby"),
                    ("maintenance", "Maintenance"),
                    ("overnight", "Overnight"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="aircraftnote",
            name="transportation_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "None"),
                    ("personal", "Personal"),
                    ("driver", "Driver"),
                    ("rental", "Rental"),
                    ("self-park", "Self-Park"),
                    ("Ride Share", "Ride Share"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
