# Generated by Django 4.1.13 on 2023-12-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aircraft", "0003_alter_aircraftnote_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aircraftnote",
            name="aircraft_model",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="aircraftnote",
            name="location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hanger_1", "H1"),
                    ("hanger_2", "H2"),
                    ("hanger_3", "H3"),
                    ("hanger_4", "H4"),
                    ("row_1", "R1"),
                    ("row_2", "R2"),
                    ("row_3", "R3"),
                    ("row_4", "R4"),
                    ("row_5", "R5"),
                    ("row_6", "R6"),
                    ("tie_down", "T-D"),
                    ("gama", "Gama"),
                    ("off_ramp", "O-R"),
                    ("customs", "Cstm"),
                    ("netjets", "NJ"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="aircraftnote",
            name="tail_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
